#!/usr/bin/env python3
"""Regenerate the index at the top of .claude/lessons_learned.md.

PARSED, never hand-written. An index is a second copy of what the document already says, and a
hand-maintained one drifts -- that is how docs/image_inventory.md ended up with three parallel
tables and two contradictory tallies. This reads the lessons themselves, so it cannot disagree
with them, and re-running it is the only way to change it.

It works because every lesson has the same rigid shape:

    ## <section>
    ### `L-SLUG`

    **The one-line statement, which may wrap across two lines.**

    ...body...

so the slug comes off the ### header and the hook comes off the first bolded run after it.

  python scripts/gen_lessons_index.py             rewrite the index in place
  python scripts/gen_lessons_index.py --check     exit 1 if it is stale (nothing written)

Run it after adding or renaming a lesson. Renaming matters most: slugs are cited across the repo
precisely so a stale citation breaks loudly, and the index is one more place a rename has to reach.
"""
import argparse
import io
import os
import re
import sys

DOC = os.path.join('.claude', 'lessons_learned.md')
BEGIN = '<!-- INDEX:BEGIN (generated by scripts/gen_lessons_index.py -- do not hand-edit) -->'
END = '<!-- INDEX:END -->'
HOOK_CHARS = 116


def strip_index(text):
    """The document without its index block, so parsing never sees its own output."""
    return re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n*', '', text, flags=re.S)


def anchor(slug):
    """GitHub-style anchor for a '### `L-SLUG`' header: lowercased, backticks dropped."""
    return '#' + slug.lower()


def parse(text):
    """[(section, slug, hook)] in document order."""
    out, section, slug, buf = [], None, None, []

    def flush():
        if slug:
            out.append((section, slug, hook_from(buf)))

    for line in text.split('\n'):
        m_sec = re.match(r'^## +(.+?)\s*$', line)
        m_les = re.match(r'^### +`(L-[A-Z0-9-]+)`\s*$', line)
        if m_sec:
            flush()
            section, slug, buf = m_sec.group(1), None, []
        elif m_les:
            flush()
            slug, buf = m_les.group(1), []
        elif slug:
            buf.append(line)
    flush()
    return out


def hook_from(body):
    """The lesson's own opening statement.

    Most lessons open with a **bolded** thesis that may wrap across lines, and that is the hook.
    Two do not (L-CAPABILITY-CEILINGS, L-I2VA-VS-L2VA-COMPLETENESS), and searching the whole body
    for a bold run gave them mid-sentence fragments -- "I2VA gaze", "by design". So the bold is
    only trusted when it OPENS the first paragraph; otherwise take that paragraph as prose.
    """
    start = next((i for i, l in enumerate(body) if l.strip()), None)
    if start is None:
        return ''
    para = []
    for line in body[start:]:
        if not line.strip():
            break
        para.append(line)
    text = '\n'.join(para).strip()

    m = re.match(r'\*\*(.+?)\*\*', text, re.S)
    hook = m.group(1) if m else text
    hook = re.sub(r'^[-*]\s+', '', hook)              # a paragraph that starts as a bullet
    hook = re.sub(r'\*\*(.+?)\*\*', r'\1', hook, flags=re.S)   # inline emphasis
    hook = re.sub(r'(?<!\*)\*([^*]+)\*(?!\*)', r'\1', hook)
    hook = ' '.join(hook.split()).strip(' .:')
    if len(hook) > HOOK_CHARS:
        hook = hook[:HOOK_CHARS].rsplit(' ', 1)[0] + '...'
    return hook


def render(entries):
    lines = [BEGIN, '## The lessons at a glance', '',
             '*Generated from the headings below by `scripts/gen_lessons_index.py`. '
             'Add a lesson, then re-run it.*', '']
    last = None
    for section, slug, hook in entries:
        if section != last:
            lines += ['', f'**{section}**', '']
            last = section
        lines.append(f'- [`{slug}`]({anchor(slug)}) — {hook}')
    lines += ['', END]
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if the index is out of date; write nothing')
    ap.add_argument('--doc', default=DOC)
    a = ap.parse_args()

    original = io.open(a.doc, encoding='utf-8').read()
    body = strip_index(original)
    entries = parse(body)
    if not entries:
        raise SystemExit(f'ERROR: no "### `L-SLUG`" headers found in {a.doc}')

    # The index goes directly above the first section heading, after the preamble.
    m = re.search(r'^## ', body, re.M)
    if not m:
        raise SystemExit(f'ERROR: no "## " section heading found in {a.doc}')
    updated = body[:m.start()] + render(entries) + '\n\n' + body[m.start():]

    if updated == original:
        print(f'{a.doc}: index is current ({len(entries)} lessons)')
        return 0
    if a.check:
        print(f'{a.doc}: index is STALE ({len(entries)} lessons found) -- '
              f'run scripts/gen_lessons_index.py')
        return 1
    io.open(a.doc, 'w', encoding='utf-8', newline='\n').write(updated)
    print(f'wrote {a.doc}: {len(entries)} lessons in '
          f'{len({s for s, _, _ in entries})} sections')
    return 0


if __name__ == '__main__':
    sys.exit(main())