#!/usr/bin/env python3
"""Generate a bare sweep of images/ against one describer prompt.

Unlike gen_style_sweep.py this reads NOTHING from docs/image_inventory.md — it enumerates
the folder and emits a run_tests.py case file with no answer key. That makes it usable for
roles whose ground truth does not exist yet, which is the point: the character-age test and
the setting drift check both need a case skeleton over the corpus before anything can be
scored, and hand-building 187 cases is how generators get written ad hoc and then lost.

    python scripts/gen_sweep.py frame                          # to stdout
    python scripts/gen_sweep.py frame --limit 3 -o /tmp/x.json # a 3-image smoke sweep
    python scripts/gen_sweep.py character --expected-skeleton  # pre-keyed answer key

Output goes to STDOUT by default. Nothing is written anywhere unless you pass -o, and -o
refuses to overwrite an existing file without --force — regenerating a baselined test over a
grown corpus breaks its comparison silently (see gen_style_sweep.py's warning).

A full sweep is 187 inferences per role, 374 for style. Use --limit while iterating.
"""
import argparse, fnmatch, io, json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from inventory import IMG_DIR, EXTS                    # noqa: E402

# Copied from tests/describer_frame.json so a sweep runs under the same sampler settings as
# every other round. `system_file` is filled in per role below.
DEFAULTS = {
    'server': 'http://localhost:8080/v1/chat/completions',
    'model': 'qwen3.6-35b-a3b',
    'temperature': 0,
    'top_p': 0.9,
    'top_k': 40,
    'max_tokens': 2048,
}

# The only role-specific data in the script. Adding a fifth describer means one entry.
#
# `style` is the odd one: describer_style_class.txt classifies from the LOOK pass's record,
# so each image needs two cases and the look case must come first — run_tests.py resolves
# {{...}} only against cases already run in the same invocation.
ROLES = {
    'frame':     {'prefix': 'fr',  'prompt': 'prompts/describer_frame.txt',
                  'user': 'ROLE: frame'},
    'character': {'prefix': 'ch',  'prompt': 'prompts/describer_character.txt',
                  'user': 'ROLE: character'},
    'setting':   {'prefix': 'set', 'prompt': 'prompts/describer_setting.txt',
                  'user': 'ROLE: setting'},
    'object':    {'prefix': 'ob',  'prompt': 'prompts/describer_object.txt',
                  'user': 'ROLE: object'},
    'style':     {'prefix': 'sw',  'prompt': 'prompts/describer_style_class.txt',
                  'user': 'ROLE: style',
                  'look_prompt': 'prompts/describer_style_look.txt'},
}


def slugify(stem):
    """Reduce a filename stem to characters the harness grammars can carry.

    run_tests.py matches substitution ids as [^{}:]+ and validate.py anchors a record header
    on the trailing [...], so a `{`, `:` or `]` in a filename would corrupt either one.
    """
    return re.sub(r'[^A-Za-z0-9_-]', '_', stem)


def collect(img_dir, match, exclude, limit):
    """Filenames in img_dir, filtered and sorted case-insensitively for a diffable file."""
    names = [f for f in os.listdir(img_dir)
             if os.path.splitext(f)[1].lower() in EXTS]
    if match:
        names = [f for f in names if any(fnmatch.fnmatch(f, p) for p in match)]
    names = [f for f in names if not any(fnmatch.fnmatch(f, p) for p in exclude)]
    names.sort(key=lambda f: (f.lower(), f))
    return names[:limit] if limit else names


def slugs_for(names):
    """Map each filename to a unique slug.

    gen_style_sweep.py keys a dict by stem, which silently drops one of foo.jpg / foo.png.
    A sweep has to cover every file, so a collision falls back to stem_ext and then to a
    numeric suffix.
    """
    out, taken = [], set()
    for name in names:
        stem, ext = os.path.splitext(name)
        slug = slugify(stem)
        if slug in taken:
            slug = slugify(stem + '_' + ext.lstrip('.'))
            n = 2
            while slug in taken:
                slug, n = f'{slugify(stem)}_{n}', n + 1
        taken.add(slug)
        out.append((name, slug))
    return out


def build(role, names, img_dir, skeleton, argv):
    spec = ROLES[role]
    cases, scorable = [], []

    for name, slug in slugs_for(names):
        img = f'{img_dir}/{name}'
        cid = f'{spec["prefix"]}_{slug}'
        if 'look_prompt' in spec:
            look_id = f'look_{slug}'
            cases.append({'id': look_id, 'user': spec['user'], 'image': img,
                          'system_file': spec['look_prompt']})
            cases.append({'id': cid,
                          'user': f'{spec["user"]}\n\n[[STYLE_RECORD]]\n{{{{{look_id}}}}}',
                          'image': img, 'system_file': spec['prompt']})
        else:
            cases.append({'id': cid, 'user': spec['user'], 'image': img})
        scorable.append(cid)

    doc = {
        '_note': 'Generated by scripts/gen_sweep.py — a bare sweep of every image in '
                 f'{img_dir}/ against the {role} describer. No answer key: this exists to '
                 'be read by eye, or to seed one.',
        '_role': role,
        '_generated': 'scripts/gen_sweep.py ' + ' '.join(argv),
        '_expected': {cid: 'TODO' for cid in scorable} if skeleton else {},
    }
    if skeleton:
        doc['_expected_note'] = (
            'Skeleton only. Every value is the literal string TODO, which score.py will '
            'report as a miss until it is replaced with the real field values — an unfilled '
            'key should fail loudly, not pass silently.')

    defaults = dict(DEFAULTS)
    if 'look_prompt' not in spec:
        defaults['system_file'] = spec['prompt']
    # else: the two passes use different prompts, so system_file is per case (as in
    # gen_style_sweep.py). Leaving a default here would mask a missing per-case value.
    doc['defaults'] = defaults
    doc['cases'] = cases
    return doc


def main():
    ap = argparse.ArgumentParser(
        description='Generate a bare run_tests.py sweep of images/ for one describer role.')
    ap.add_argument('role', choices=sorted(ROLES))
    ap.add_argument('-o', '--out', help='write here instead of stdout')
    ap.add_argument('--force', action='store_true',
                    help='allow -o to overwrite an existing file')
    ap.add_argument('--images', default=IMG_DIR, help=f'image directory (default {IMG_DIR})')
    ap.add_argument('--match', metavar='GLOB', action='append', default=[],
                    help='keep only filenames matching GLOB (repeatable)')
    ap.add_argument('--exclude', metavar='GLOB', action='append', default=[],
                    help='drop filenames matching GLOB (repeatable, wins over --match)')
    ap.add_argument('--limit', type=int, metavar='N', help='first N images after filtering')
    ap.add_argument('--expected-skeleton', action='store_true',
                    help='pre-key _expected with every scorable case id, valued TODO')
    args = ap.parse_args()

    if not os.path.isdir(args.images):
        raise SystemExit(f'ERROR: no such image directory: {args.images}')
    if args.out and os.path.exists(args.out) and not args.force:
        raise SystemExit(f'ERROR: {args.out} exists — pass --force to overwrite. '
                         'Regenerating a baselined test breaks its comparison silently.')

    names = collect(args.images, args.match, args.exclude, args.limit)
    if not names:
        raise SystemExit(f'ERROR: no images matched in {args.images}')

    doc = build(args.role, names, args.images.replace(os.sep, '/'),
                args.expected_skeleton, sys.argv[1:])
    text = json.dumps(doc, indent=2, ensure_ascii=False) + '\n'

    if args.out:
        io.open(args.out, 'w', encoding='utf-8', newline='\n').write(text)
    else:
        sys.stdout.write(text)
    print(f'{args.role}: {len(names)} images, {len(doc["cases"])} cases'
          + (f' -> {args.out}' if args.out else ''), file=sys.stderr)


if __name__ == '__main__':
    main()
